// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVxFkKTDa8F_H3QfUgDW0X78AlOEx_39U',
    appId: '1:838093881502:web:135b0a457ee802b8d9bb8f',
    messagingSenderId: '838093881502',
    projectId: 'higate-quiz-game',
    authDomain: 'higate-quiz-game.firebaseapp.com',
    databaseURL: 'https://higate-quiz-game-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'higate-quiz-game.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQa5PjP_VjYpGuJX8l99gGjr4PY4941NY',
    appId: '1:838093881502:android:1020fb3e7be4acf8d9bb8f',
    messagingSenderId: '838093881502',
    projectId: 'higate-quiz-game',
    databaseURL: 'https://higate-quiz-game-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'higate-quiz-game.appspot.com',
  );
}
